---
title: "Data Article: Trier social stress test and food-choice: Behavioral, self-report & hormonal data"
author: "Felix Jan Nitsch; Manuela Sellitto; Tobias Kalenscher"
date: "June, 25 2021"
output:
  html_document:
    df_print: paged
bibliography: references.bib
---

Citation to original version of this data article:

Nitsch, F. J., Sellitto, M., & Kalenscher, T. (2021). Trier social stress test and food-choice: Behavioral, self-report & hormonal data. Data in brief (**FIXME1**), *37*, 107245. https://doi.org/10.1016/j.dib.2021.107245 (**FIXME2**)

**Abstract**

A sample of 144 participants underwent the Trier Social Stress Test (TSST), a psychosocial stress manipulation involving a mock interview and a mental arithmetic task, or a matched control procedure. Physiological stress was estimated via a collection of 7 saliva samples over the course of the experiment analysed for cortisol and alpha-amylase, as well as via the mean heart-rate measured before and during the experimental manipulation. Subjective stress was assessed via the Positive and Negative Affect Scale as well as four Visual Analogue Scales at 6 points over the time course of the experiment. Participants solved an incentive-compatible food-choice task before, immediately after and in the aftermath of the experimental manipulation. In each trial of the food-choice task, participants had to choose one out of a set of two to seven snack bundles. Each snack bundle consisted of specific amounts of a sweet or salty snack and a fruit or vegetable. The snacks for both categories were selected to be similarly attractive according to the previously provided online ratings of the participants. The design of the food-choice task allows for the calculation of revealed preference consistency indices. The dataset further contains several self-report questionnaires administered to the participants before the experimental session, including the Trier Inventory of Chronic Stress.

## **Keywords**

Acute stress; Amylase Choice Consistency; Cortisol; Chronic StressFood-Choice; Rationality.

**Specifications Table** (**FIXME3**)

+:-------------------------------+:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Subject                        | Neuropsychology and Physiological Psychology                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
+--------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Specific subject area          | Psychoneuroendocrinology, Behavioral Economics, Psychology of Stress                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
+--------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Type of data                   | Primary data                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
+--------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| How data were acquired         | Data was gathered using an online survey platform (Unipark), as well as computerized tasks and pen-and-paper questionnaires in a laboratory for measurement of behavior. English translations of all materials are available in the online repository.                                                                                                                                                                                                                                                                    |
+--------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Data format                    | Raw\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                                | Analysed\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|                                | Figures                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
+--------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Parameters for data collection | The data was obtained from 144 participants in Germany. Participants did not have formal psychological or economic education, were 18--40 years old, non-smokers and did not take medication that could have influenced their corticosteroid levels. Women were not taking oral contraceptives. Similar to previous studies, participants had to refrain from drinking alcohol and sexual activities for 24 h, caffeine four hours and eating/drinking (except water) two hours prior to the beginning of the experiment. |
+--------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Description of data collection | Participants were recruited via flyers on the university campus, postings in student Whatsapp and Facebook groups and the university job portal (convenience sample).                                                                                                                                                                                                                                                                                                                                                     |
+--------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Data source location           | Institution: Heinrich-Heine-University Düsseldorf\                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                                | City/Town/Region: Düsseldorf, Northrhine-Westphalia\                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                                | Country: Germany\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|                                | Latitude and longitude for collected samples/data: 51.233334, 6.783333                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+--------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Data accessibility             | Repository name: Open Science Framework (OSF)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|                                | Data identification number: DOI 10.17605/OSF.IO/6MVQ7\                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|                                | Direct URL to data: <https://osf.io/6mvq7/>                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
+--------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Related research article       | Nitsch, F. J., Sellitto, M., & Kalenscher, T. (2021). The effects of acute and chronic stress on choice consistency. Psychoneuroendocrinology, 131, 105289. <https://doi.org/10.1016/j.psyneuen.2021.105289>                                                                                                                                                                                                                                                                                                              |
+--------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## **Value of the Data** 

(**FIXME4**)

The data are useful, as both the analysis of salivary cortisol for a relatively large sample as well as the implementation of an incentive-compatible behavioral task are expensive. Further, data sharing in the field of choice consistency/rationality is still relatively uncommon, making the aggregation of evidence   challenging @nitsch2020b

The data is valuable to researchers interested in the interplay of physiological and subjective stress. It enables exploratory data-analysis regarding individual differences in stress reactivity and mediators of the stress response.

The unprocessed behavioral data may be used to investigate stress and behavior interactions in economic choice.

The pre-processed data might be used for evidence aggregation in the field of choice consistency/rationality in the future.

## **1. Data Description**

This [OSF](https://osf.io/6mvq7/) directory contains the raw and processed data described, as well as analysis scripts required to computationally reproduce the results and plots reported in the *related research article*. The structure of the directory is:

### Analysis 
*modified for this workshop from the original directory structure in OSF

-   R Studio Project File

    - code (contains all runnable R script files)

    - data (contains raw data)
      
      - food choice-data (contains raw data from food-choice task)

    - output (contains all generated output)

      - data (contains pre-processed data)

      - plots (contains all plots)
    
    - report (contains all files for publication)
      
      - source (contains rmd file, figs, bibliography)
      
      - output (contains rendered html publication)

To repeat the analyses of the *related research article*, follow the instructions in the README file.

### Materials

-   Questionnaires (contains English translations of the administered questionnaire)

-   Snack-Pictures (contains all snack pictures used in the food-choice Task)

Here, we will focus on the description of raw and processed data files.

File: root/data/GARP-TSST-mastersheet.xlsx (\_raw data\_)

Description: The excel file consists of four worksheets. The first sheet ("Master-sheet") contains the raw data of all measures collected during the experimental session except the food-choice task data. The second sheet ("Code-sheet") contains a description of all columns in the Master-sheet. The third sheet ("Saliva-Sample-Encoding") contains excel code matching the IDs of the saliva samples to corresponding participant IDs. The fourth sheet ("Salivettes-Data") contains the raw data for cortisol and amylase measurements that we received from the commercial analysis lab. Typically, users of the data will only import the first sheet into their analysis environment and refer to the Code sheet for further information.

File: root/data/online_data_cleaned.xlsx (\_raw data\_)

Description: The excel file consists of two worksheets. The first sheet ("Online-Data") contains the raw data of all measures collected during the online survey before the experimental session. The data was cleaned of all identifying information and the survey ID was replaced by the corresponding participant ID. Hence, the file can be readily merged with the Master-sheet by the participant ID column. The second sheet ("Code-sheet") contains a description of all columns in the first sheet. Typically, users of the data will only import the first sheet into their analysis environment and refer to the Code-sheet for further information.

File: root/data/foodchoice-budgetlines.CSV (\_raw data\_)

Description: contains all 22 possible economic parameter combinations which were sampled in the food-choice task (see Experimental Design, Materials & Methods). Each row of the file represents the economic parameters of one possible trial. The first column "m" contains the untransformed budget. The second column "px" contains the price per piece of the sweet/salty snack in untransformed budget units. The third column "py" contains the price per piece of the fruit/vegetable snack in untransformed budget units. The fourth column "px/py" contains the relative price ratio, that is the steepness of the budgetline.

File: root/data/bronars_simulation_data.csv (\_raw data\_)

The CSV file contains choice consistency data for 10.000 (**FIXME8**) simulated participants, that have been used to determine the power of our food-choice task design to detect choice consistency violations. Simulated participants solved one measurement (11 trials) of the food-choice task (see Experimental Design, Materials & Methods). Simulated choices were uniform-random among the choice sets. Column 1 and 2 ("filename", "VP") are redundant and contain the participant IDs. Column 3 ("Session") indicates the number of measurements (always 1 here). Column 4 ("violation_count") indicates the number of trials involved in a revealed preference inconsistency [see 2]. Column 5 ("AI") contains the critical cost efficiency index @nitsch2020a; ,@afriat1972. Column 6 ("mean_RT") contains the mean reaction times (arbitrary). Typically, users of the data will only use the information in column 4 and 5 ("violation_count", "AI").

File: root/data/foodchoice_data/CC-\$VPN\_\$Measurement_data.csv (\_raw data\_)

\$VPN = Participant ID (101-269). \$Measurement = Measurement (1-3). Each CSV file contains the raw and untidy data output of the food-choice task. Generally, the files consist of two blocks. The first block consists of columns 1 to 11 ("0", "1", "10", "2", "3", "4", "5", "6", "7", "8", "9"). It contains the information for the 11 trials of the food-choice task of the corresponding participant and measurement. Row 1 ("MISSES") indicates how often participants failed to make a response for a given trial within 60 s. Missed trials were repeated at the end of the measurement in random order, until a response was given. Row 2 ("RT") contains the reaction time in seconds. Row 3 ("choice_set") contains all available snack bundles in that trial. Row 4 ("m") contains the untransformed budget. Row 5 column ("px") contains the price per piece of the sweet/salty snack in untransformed budget units. Row 6 ("py") contains the price per piece of the fruit/vegetable snack in untransformed budget units. Row 7 ("sbundle") contains the chosen snack bundle in that trial. Row 8 ("trial_nr") contains the trial number (1-11) a given trial was first presented. The second block consists of columns 12 to 17 ("Snack_G", "Snack_UG", "Testung", "VP_Code", "endtime", "starttime"). For this this block every row contains the same information (redundant). Column "Snack_G" contains the name of the fruit/vegetable snack. Column "Snack_UG" contains the name of the sweet/salty snack. "Testung" contains the measurement. "VP_Code" contains the participant ID. Column "endtime" contains the endtime of the food-choice task. Column "starttime" contains the starttime of the food-choice task. Typically, users will need to clean and pre-process the data before analysis.

File: root/output/data/preprocessed-GARP-TSST-data.csv (\_pre-processed data\_)

The CSV file contains the data of the first sheet of the mastersheet (root/data/GARP-TSST-mastersheet.xlsx) and three additional columns ("CCEI_1", "CCEI_2", "CCEI_3"). These columns contain the critical cost efficiency index for each measurement of the food-choice task. These columns were calculated from the raw food-choice data (root/data/foodchoice_data/CC-\$VPN\_\$Measurement_data.csv) using the pre-processing R script (root/analysis_scripts/01_data_preprocessing.R).

\

## **2. Experimental Design, Materials and Methods**

The dataset contains data of 144 participants. Participants did not have formal psychological or economic education, were 18--40 years old, non-smokers and did not take medication that could have influenced their corticosteroid levels. Women were not taking oral contraceptives. Similar to previous studies, participants had to refrain from drinking alcohol and sexual activities for 24 h, from caffeine for four hours and from eating/drinking (except water) for two hours prior to the beginning of the experiment.

(**FIXME5**)

[Fig. 1 provides an exact overview of the experimental timeline for each measure we collected. All experimental sessions took place from 3 p.m. to 6 p.m. to control for circadian variations of hormonal levels. Participants were assigned to the two experimental conditions pseudo-randomly.]

Our food-choice task was administered following a 2 × 3 mixed-factorial design with Experimental Group (stress vs. control) as between-subject factor and Measurement (Baseline, Early, Late) as within-subject factor. We deployed a standard food-choice task similar to the one used by @harbaugh2001 and @chung2017 . In each trial, participants chose one out of a set of two to seven snack bundles. Each snack bundle consisted of specific amounts of a sweet or salty snack and a fruit or vegetable (see [Fig. 2]). The choice set was defined by all integer combinations of sweet or salty snack and fruit or vegetable on the budget-line. The budget-line was given by the following formula:

(**FIXME7**)
Amount (fruit/vegetable) = - px/py  Amount (sweet/salty) + m/py

(**FIXME6**)

[The figure displays the choice sets of 4 example trials of the food-choice task. The economic parameters for these were for A: m = 4, px = 1, py = 1; for B: m = 2, px = 2, py = 1; for C: m = 2, px = 1, py = 2; for D: m = 5, px = 1, py = 1. The available snack bundles are then given by all integer combinations of both snack types along the budgetline. The budgetline is given by the formula:]


At each of the three measurements, participants had to make decisions in 11 trials. The economic parameters ("px", "py", "m") of the 11 trials for each time point were randomly sampled from a collection of 22 possible parameter combinations (see file root/data/foodchoice_budgetlines.csv). The snacks for both categories were similarly attractive according to the previously provided online ratings of the participants (see file root/data/online_data_cleaned.xlsx). The sampling procedure was implemented to reduce interdependency of the answers of each participant for subsequent time points, while keeping the presented bundle size out of satiation range. At the end of the experiment, one trial was randomly selected for each participant, and their choice in that trial was implemented, i.e., participants received their chosen snack bundle. The experimental task was presented via PsychoPy @peirce2007. For 8 participants (out of N = 144 participants), no or incomplete food-choice data were saved due to a technical failure of the experimental hardware.

Our physiological and subjective stress measures were all assessed following a similar mixed-factorial design. However, the exact Measurement regime varied between measures. Self-report trait questionnaires were administered before the experimental session via an online survey (Unipark). An English translation of the administered questionnaires can be found in the online repository.

We collected saliva samples with Salivette devices (Sarstedt, Germany) that consist of a cotton wool swab that participants chewed on lightly for 60 s, allowing the swab to fill with saliva. All samples were frozen and stored at −20 degree Celsius and analysed by a commercial lab (Dresden LabService GmbH) for cortisol and alpha-amylase. Cortisol and alpha-amylase concentrations were determined using a luminescent immunoassay (IBL International, Hamburg). For 16 samples analysis of cortisol and/or alpha-amylase was not possible due to insufficient saliva or contamination with blood.

## Preview of Research Results

FIXME add Fig 3 - heart rate analysis


FIXME add Fig 4: Cortisol and Amylase levels in stress and control groups


All analyses were conducted in R[^1] in the RStudio IDE[^2] using the packages Tidyverse (**add citation here**), stringi[^3], BayesFactor[^4] and patchwork[^5].

[^1]: [<https://www.R-project.org/>](https://www.r-project.org/)

[^2]: <https://www.rstudio.com/>

[^3]: <https://stringi.gagolewski.com/>

[^4]: [<https://CRAN.R-project.org/package=BayesFactor>](https://cran.r-project.org/package=BayesFactor)

[^5]: <https://CRAN.R-project.org/package=patchwork>

## Ethics Statement

All participants gave their informed written consent before participation. The study protocol was approved by the ethical council of the medical faculty of Heinrich-Heine-University Düsseldorf (Study-Nr.: 2020-910). The study was conducted in alignment with the declaration of Helsinki.

## CRediT Author Statement

Felix Jan Nitsch: Conceptualization, Methodology, Software, Validation, Formal Analysis, Investigation, Data Curation, Writing - Original draft preparation, Project Administration; Manuala Sellitto: Data curation, Writing - Review & Editing, Supervision; Tobias Kalenscher: Conceptualization, Resources, Writing - Review & Editing, Supervision, Funding Acquisition.

\

## Declaration of Competing Interest

The research was supported by a grant from the Deutsche Forschungsgemeinschaft (Bonn, Germany) to Tobias Kalenscher (grant-ID: DFG-KA: DFG-KA 2675/4-3).

The authors declare that they have no known competing financial interests or personal relationships which have or could be perceived to have influenced the work reported in this article.

## Acknowledgments

We thank Adam Schweda for helpful comments on the study design as well as assistance with the data collection. We thank Johanna Falk, Anne Schmittner, Jochen Hoog, Alina Keßler and Paul Kramer for assistance with data collection.

## Appendix. Supplementary materials

[Download: Download zip file (1MB)](https://ars.els-cdn.com/content/image/1-s2.0-S2352340921005291-mmc1.zip)

##  References

\
